# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  # Development
  dev:cli:
    desc: Run CLI in dev mode
    dir: apps/cli
    cmds:
      - go run .

  dev:platform:
    desc: Run platform in dev mode
    dir: apps/platform
    cmds:
      - bun run dev

  dev:runner:
    desc: Run runner in dev mode
    dir: apps/runner
    cmds:
      - uv run fastapi dev src/oken_runner/server.py

  # Build
  build:cli:
    desc: Build CLI binary
    dir: apps/cli
    cmds:
      - go build -o oken .

  build:platform:
    desc: Build platform
    dir: apps/platform
    cmds:
      - bun run build

  # Database
  db:generate:
    desc: Generate Drizzle migrations
    dir: apps/platform
    cmds:
      - bunx drizzle-kit generate

  db:migrate:
    desc: Run Drizzle migrations
    dir: apps/platform
    cmds:
      - bunx drizzle-kit migrate

  # Linting and formatting
  lint:runner:
    desc: Lint and type-check runner
    dir: apps/runner
    cmds:
      - uv run ruff check src/
      - uv run ty check src/

  format:runner:
    desc: Format runner code
    dir: apps/runner
    cmds:
      - uv run ruff format src/
      - uv run ruff check src/ --fix

  check:runner:
    desc: Run all checks for runner (lint, type-check, format check)
    dir: apps/runner
    cmds:
      - uv run ruff format src/ --check
      - uv run ruff check src/
      - uv run ty check src/

  test:runner:
    desc: Run all runner tests
    dir: apps/runner
    cmds:
      - uv run pytest

  test:runner:unit:
    desc: Run runner unit tests (no Docker required)
    dir: apps/runner
    cmds:
      - uv run pytest -m "not integration"

  test:runner:integration:
    desc: Run runner integration tests (requires Docker)
    dir: apps/runner
    cmds:
      - uv run pytest -m integration

  test:runner:cov:
    desc: Run runner tests with coverage
    dir: apps/runner
    cmds:
      - uv run pytest --cov=oken_runner --cov-report=term-missing
