# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  # ====================
  # Development
  # ====================
  dev:cli:
    desc: "[dev] Run CLI in dev mode"
    dir: apps/cli
    cmds:
      - go run .

  dev:platform:
    desc: "[dev] Run platform on :3000"
    dir: apps/platform
    cmds:
      - bun run dev

  dev:runner:
    desc: "[dev] Run runner on :8000"
    dir: apps/runner
    cmds:
      - uv run fastapi dev src/oken_runner/server.py

  # ====================
  # Build
  # ====================
  build:cli:
    desc: "[build] Build CLI binary"
    dir: apps/cli
    cmds:
      - go build -o oken .

  build:platform:
    desc: "[build] Build platform for production"
    dir: apps/platform
    cmds:
      - bun run build

  # ====================
  # Database
  # ====================
  db:start:
    desc: "[db] Start local PostgreSQL (Docker)"
    cmds:
      - docker compose -f infra/postgres.yml up -d

  db:stop:
    desc: "[db] Stop local PostgreSQL"
    cmds:
      - docker compose -f infra/postgres.yml down

  db:generate:
    desc: "[db] Generate Drizzle migrations"
    dir: apps/platform
    cmds:
      - bunx drizzle-kit generate

  db:migrate:
    desc: "[db] Run Drizzle migrations"
    dir: apps/platform
    cmds:
      - bunx drizzle-kit migrate

  # ====================
  # Lint
  # ====================
  lint:runner:
    desc: "[lint] Runner - ruff + ty"
    dir: apps/runner
    cmds:
      - uv run ruff check src/
      - uv run ty check src/

  lint:platform:
    desc: "[lint] Platform - biome"
    dir: apps/platform
    cmds:
      - bunx biome lint .

  # ====================
  # Format
  # ====================
  format:runner:
    desc: "[format] Runner - ruff"
    dir: apps/runner
    cmds:
      - uv run ruff format src/
      - uv run ruff check src/ --fix

  format:platform:
    desc: "[format] Platform - biome"
    dir: apps/platform
    cmds:
      - bunx biome format --write .

  # ====================
  # Check (lint + format)
  # ====================
  check:runner:
    desc: "[check] Runner - lint, type-check, format"
    dir: apps/runner
    cmds:
      - uv run ruff format src/ --check
      - uv run ruff check src/
      - uv run ty check src/

  check:platform:
    desc: "[check] Platform - lint, format, imports"
    dir: apps/platform
    cmds:
      - bunx biome check --write .

  # ====================
  # Test
  # ====================
  test:runner:
    desc: "[test] Runner - all tests"
    dir: apps/runner
    cmds:
      - uv run pytest

  test:runner:unit:
    desc: "[test] Runner - unit only (no Docker)"
    dir: apps/runner
    cmds:
      - uv run pytest -m "not integration"

  test:runner:integration:
    desc: "[test] Runner - integration (requires Docker)"
    dir: apps/runner
    cmds:
      - uv run pytest -m integration

  test:runner:cov:
    desc: "[test] Runner - with coverage"
    dir: apps/runner
    cmds:
      - uv run pytest --cov=oken_runner --cov-report=term-missing

  test:platform:
    desc: "[test] Platform - unit tests"
    dir: apps/platform
    cmds:
      - bun run test

  test:platform:integration:
    desc: "[test] Platform - integration tests (requires Docker)"
    dir: apps/platform
    cmds:
      - bunx vitest run --config vitest.integration.config.ts

  test:platform:cov:
    desc: "[test] Platform - with coverage"
    dir: apps/platform
    cmds:
      - bunx vitest run --coverage
