services:
  postgres:
    image: postgres:18-alpine
    container_name: oken-postgres
    environment:
      POSTGRES_USER: oken
      POSTGRES_PASSWORD: oken
      POSTGRES_DB: oken
    ports:
      - "5432:5432"
    volumes:
      - oken-postgres-data:/var/lib/postgresql

volumes:
  oken-postgres-data:
